config/routes.rb
Rails.application.routes.draw do
  root 'users#index'

  resources :users
  resource :session, only: %i[new create destroy]
  resources :questions, except: %i[index new show]
  resources :hashtags, only: :show, param: :name
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hashtag.rb
class Hashtag < ApplicationRecord
  HASHTAG_FORMAT = /#[[:word:]-]+/

  has_many :taggings, dependent: :destroy
  has_many :questions, through: :taggings

  scope :with_questions, -> { where_exists(:taggings) }
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true

  has_many :taggings, dependent: :destroy
  has_many :hashtags, through: :taggings

  scope :answered, -> { where.not(answer: nil) }
  scope :unanswered, -> { where(answer: nil) }

  after_commit :create_hashtag, on: %i[create update]

  validates :text, presence: true, length: { maximum: 255 }

  def create_hashtag
    self.hashtags = "#{text} #{answer}".
      downcase.
      scan(Hashtag::HASHTAG_FORMAT).
      uniq.
      map{ |hashtag| Hashtag.create_or_find_by(name: hashtag.delete("#")) }
  end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :question
  belongs_to :hashtag
end

app/models/user.rb
class User < ApplicationRecord
  ITERATIONS = 20000
  DIGEST = OpenSSL::Digest::SHA256.new
  EMAIL_FORMAT = /\A\w+@\w+\.\w+\z/
  USERNAME_FORMAT = /\A\w+\z/
  COLOR_FORMAT = /\A#\h{3}{1,2}\z/

  attr_accessor :password

  has_many :questions, dependent: :destroy

  before_validation :convert_to_downcase
  before_save :encrypt_password
  before_update :color

  validates :username,
            presence: true,
            uniqueness: true,
            length: { maximum: 40 },
            format: { with: USERNAME_FORMAT }

  validates :email,
            presence: true,
            uniqueness: true,
            format: { with: EMAIL_FORMAT }

  validates :password,
            confirmation: true,
            presence: true,
            on: :create

  validates :color,
            format: { with: COLOR_FORMAT }

  def self.authenticate(email, password)
    user = find_by(email: email&.downcase)
    user if user.present? && user.password_hash == User.hash_to_string(
      OpenSSL::PKCS5.pbkdf2_hmac(
        password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST
        )
      )
  end

  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  private

  def convert_to_downcase
    username&.downcase!
    email&.downcase!
  end

  def encrypt_password
    if password.present?
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))
      self.password_hash = User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(
          password, password_salt, ITERATIONS, DIGEST.length, DIGEST
        )
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  private
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def reject_user
    redirect_to root_path, alert: t('.not_allowed')
  end
end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController
  def show
    hashtag = Hashtag.with_questions.find_by!(name: params[:name])
    @questions = hashtag.questions
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: %i[edit update destroy]
  before_action :authorize_user, except: [:create]

  def create
    Questions::Create.(
      params: question_create_params,
      current_user: current_user
    ) do |m|
      m.failure :validation do |result|
        @question = result[:question]
        render :edit
      end

      m.success do |result|
        redirect_to user_path(result[:question].user), notice: t('.created')
      end
    end
  end

  def edit
  end

  def update
    if @question.update(question_update_params)
      redirect_to user_path(@question.user), notice: t('.updated')
    else
      render :edit
    end
  end

  def destroy
    user = @question.user
    @question.destroy
    redirect_to user_path(user), notice: t('.deleted')
  end

  private
  
  def load_question
    @question = Question.find(params[:id])
  end

  def authorize_user
    reject_user unless @question.user == current_user
  end

  def question_create_params
    params.require(:question).permit(:user_id, :text)
  end

  def question_update_params
    params.require(:question).permit(:answer)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(params[:email], params[:password])
    if user.present?
      session[:user_id] = user.id
      redirect_to root_path, notice: t('.signed_in')
    else
      flash.now.alert = t('.wrong_credentials')
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: t('.signed_out')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: %i[index new create]
  before_action :authorize_user, only: %i[edit update destroy]

  def index
    @users = User.all
    @hashtags = Hashtag.with_questions
  end

  def new
    redirect_to root_path, alert: t('.signed_in') if current_user.present?
    @user = User.new
  end

  def create
    redirect_to root_path, alert: t('.signed_in') if current_user.present?
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: t('.signed_up')
    else
      render 'new'
    end
  end

  def show
    @questions = @user.questions.order(created_at: :desc)
    @new_question = @user.questions.build

    @questions_count = @questions.count
    @answered_count = @questions.answered.count
    @unanswered_count = @questions.unanswered.count
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: t('.updated')
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, alert: t('.deleted')
  end

  private
  
  def authorize_user
    reject_user unless @user == current_user
  end

  def load_user
    @user ||= User.find params[:id]
  end

  def user_params
    params.require(:user).
      permit(
        :email,
        :password,
        :password_confirmation,
        :name,
        :username,
        :avatar_url,
        :color
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user_avatar(user)
    user.avatar_url.presence || asset_pack_path('media/images/avatar.jpg')
  end

  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}"
  end
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
  def text_with_hashtag_links(name)
    name&.gsub(Hashtag::HASHTAG_FORMAT) do |hashtag|
      link_to hashtag, hashtag_path(hashtag.delete('#').downcase)
    end
  end
end

app/views/hashtags/_hashtag.html.erb
<span>
  <%= link_to "##{hashtag.name}", hashtag_path(hashtag.name) %>
</span>

app/views/hashtags/show.html.erb
<div class="column-3-4">
  <div class="user-questions buffer-both">
    <% @questions.each do |question| %>
      <%= t('.question_to') %>
      <%= link_to "@#{question.user.username}", user_path(question.user) %>
      <%= render question %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8"/>
    <title><%= t('.title') %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>

    <div class="header">
      <div class="container">
        <div class="header-logo">
          <h1 class="header-title"><%= link_to t('.title'), root_path %></h1>
        </div>

        <div class="header-nav">
          <% if current_user %>
            <%= link_to "@#{current_user.username}", user_path(current_user) %> |
            <%= link_to t('.sign_out'), session_path, data: { method: :delete } %>
          <% else %>
            <%= link_to t('.sign_up'), new_user_path, class: 'button button-light button-small' %>
            <%= link_to t('.sign_in'), new_session_path, class: 'button button-light button-small' %>
          <% end %>
        </div>

      </div>
    </div>

    <div class="content">
      <div class="container">

        <% if flash.any? %>
          <div class="content-wrapper buffer-both">
            <% flash.each do |name, message| %>
              <%= content_tag :div, message, class: "flash-#{name}" %>
            <% end %>
          </div>
        <% end %>

        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/questions/_form.html.erb
<div class="form">
  <%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
      <div class="form-errors">
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li class="form-error-message"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field :user_id %>

    <div class="form-field">
      <%= f.label t('.question'), class: 'form-label' %>
      <%= f.text_area :text, class: 'form-textarea' %>
    </div>

    <% if current_user.present? && current_user == @question.user %>
      <div class="form-field">
        <%= f.label t('.answer'), class: 'form-label' %>
        <%= f.text_area :answer, class: 'form-textarea' %>
      </div>
    <% end %>

    <div class="form-action buffer-both">
      <%= f.submit t('.submit'), class: 'button button-dark button-small' %>
      <%= t('.or') %>
      <%= link_to t('.back'), user_path(@question.user) %>
    </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<div class="question">
  <div class="question-content">
    <div class="question-text text-small">
    <% if question.author.present?%>
      <%= t('.question_registered') %>
      <%= link_to "@#{question.author.username}", question.author %>
    <% else %>
      <%= t('.question_anonymous') %>
    <% end %>
    </div>

    <div class="question-text text-lead">
      <%= sanitize text_with_hashtag_links(question.text) %>
    </div>

    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= sanitize text_with_hashtag_links(question.answer) %>
      </div>
    <% end %>

    <div class="question-date">
      <%= l(question.created_at, format: :short) %>
    </div>
  </div>

  <% if question.user == current_user %>
    <% edit_icon = question.answer.blank? ? 'reply' : 'pencil' %>

    <div class="question-actions">
      <%= link_to fa_icon(edit_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question),
                  method: :delete, data: {confirm: t('.delete_confirm')} %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container content-wrapper buffer-both">
  <div class="column-1-2">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium"><%= t('.title') %></h1>

  <div class="column-1-2">
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-field">
        <%= f.label :username, class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :name, class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :avatar_url, class: 'form-label' %>
        <%= f.text_field :avatar_url, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :color, class: 'form-label' %>
        <%= f.color_field :color %>
      </div>

      <div class="buffer-top-large buffer-bottom"><%= t('.note') %></div>

      <div class="form-field">
        <%= f.label :password, class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action buffer-top">
        <%= f.submit t('.save'), class: 'button button-dark button-small' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium"><%= t('.title') %></h1>
  </div>

  <% @users.each do |user| %>
    <div class="users-list-item">
      <%= link_to image_tag(user_avatar(user), class: 'user-image-div user-image-div-small'), user_path(user) %>
    </div>
  <% end %>

  <div class="buffer-both">
    <%= render @hashtags %>
  </div>
</div>

app/views/users/new.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium"><%= t('.title') %></h1>

  <div class="column-1-2">
    <div class="form">
      <%= form_for @user do |f| %>
        <% if @user.errors.any? %>
          <div class="form-errors">
            <ul>
              <% for message in @user.errors.full_messages %>
                <li class="form-error-message"><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-field">
          <%= f.label :email, t('.email') %>
          <%= f.text_field :email, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%= f.label :username, t('.username') %>
          <%= f.text_field :username, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%= f.label :name, t('.name') %>
          <%= f.text_field :name, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%= f.label :password, t('.password') %>
          <%= f.password_field :password, class: 'form-text-field' %>
        </div>

        <div class="form-field">
          <%= f.label :password_confirmation, t('.password_confirmation') %>
          <%= f.password_field :password_confirmation, class: 'form-text-field' %>
        </div>

        <div class="form-action">
          <%= f.submit t('.submit'), class: 'button button-small button-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div style="background: <%= @user.color %>" class="user-header text-center">
  <h1 class="title-medium">
    <%= @user.name %>
  </h1>

  <div class="buffer-both">
    <%= link_to t('.edit'), edit_user_path(@user) if current_user == @user %>
  </div>

  <div class="user-image-div">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: '[Фото]' %>
  </div>

  <h2 class="title-small buffer-both">
    @<%= @user.username %>
  </h2>
</div>

<div class="container">
  <div class="buffer-both-extra-small text-center text-extra-small">
    <%= link_to t('.delete'), @user,
          method: :delete, data: {confirm: t('.delete_confirm')} if current_user == @user %>
  </div>
</div>

<div class="user-details">
  <div class="user-ask-button container text-center">
    <%= link_to t('.ask_me'), '', class: 'button button-light', id: 'ask-button' %>
  </div>

  <div class="user-statistics container text-center">
    <div class="column-1-3">
      <h1 class="title-small"><%= @questions_count %></h1>
      <p><%= I18n.t :question, count: @questions_count %></p>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= @answered_count %></h1>
      <p><%= I18n.t :answered, count: @answered_count %></p>
    </div>
    <div class="column-1-3">
      <h1 class="title-small"><%= @unanswered_count %></h1>
      <p><%= I18n.t :unanswered, count: @unanswered_count %></p>
    </div>
  </div>
</div>

<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
    <div class="form">
      <%= form_for @new_question do |f| %>
        <%= f.hidden_field :user_id %>

        <div class="form-field">
          <%= t('.question_for') %> <%= f.label "@#{@user.username}" %>
          <%= f.text_area :text, class: 'form-textarea' %>
        </div>

        <div class="form-action">
          <%= submit_tag t('.ask_question'), class: 'button button-small button-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<% if @questions.present? %>
  <div class="column-3-4">
    <div class="user-questions buffer-both">
      <div class="questions-list">
        <% @questions.each do |question| %>
          <%= render question %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>